### ISSUE TITLE
Finding items

### ISSUE THREAD

**Issue by Vanye111** [SoxMax/pathfinder-feat-graph#10]
I notice that if I search for something, it's not bringing up everything.  Specifically, I was looking for Shielded Gauntlet Style.  When searching, if I put in Shielded Gauntlet and searched, it brought up Shielded Gauntlet Attack and Master, which are the two feats that follow that, but not the Shielded Gauntlet Style, which comes before Attack.   Is that intentional?

**Comment by SoxMax** [comment]
It unfortunately is intentional. Paizo in their wisdom has named the 1st feat in the chain [Shield Gauntlet Style](https://www.aonprd.com/FeatDisplay.aspx?ItemName=Shield%20Gauntlet%20Style) while the subsequent feats are [Shielded Gauntlet Attack](https://www.aonprd.com/FeatDisplay.aspx?ItemName=Shielded%20Gauntlet%20Attack) and [Shielded Gauntlet Master](https://www.aonprd.com/FeatDisplay.aspx?ItemName=Shielded%20Gauntlet%20Master)
